branch-defaults:
  main:
    environment: filterimage-dev
deploy:
  artifacts: ./www/Archive.zip
environment-defaults:
  filterimage-dev:
    branch: null
    repository: null
global:
  application_name: filterimage
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: git
  workspace_type: Application
